### ISSUE TITLE
Fork visibility

### ISSUE THREAD

**Issue by TomaszCz** [mjablecnik/flutter_storybook#1]
It seems this repo is not listed here:

https://github.com/ookami-kb/storybook_flutter/forks

Which would be make it more visible. I personally always search for most starred forks as a potential continuation. 

I only found this package thx to this https://github.com/ookami-kb/storybook_flutter/issues/140

Btw, i encourage to add [Inspector ](https://github.com/kekland/inspector/) as a really nice feature so that this fork is complete alternative to widget book. 

Good luck!

**Comment by mjablecnik** [comment]
Hello, it's probably because I created storybook_toolkit as a new repository since every fork doesn't have the possibility to create its own issues.
This project is also in [pub.dev](https://pub.dev/packages/storybook_toolkit) so I hope it is easy to find it.
Inspector is already added in [latest version](https://github.com/mjablecnik/storybook_toolkit/commit/bb96d763a9919f69e26407a784dce481014435cd) but it is not released yet. I am going to release it during this week.

**Comment by mjablecnik** [comment]
Yesterday I released latest version of storybook_toolkit with Inspector. You can try it and let me know if everything works fine. ;)
